%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 4 -*-
---

on:
    push:
        branches:
            -   '*'

jobs:
    test_make:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: './test/ci.sh'


...
